import type { Project } from './types'

export const PROJECTS: Project[] = [
  {
    id: 'umia',
    name: 'Umia Protocol',
    av: 'av-blue',
    letter: 'U',
    cat: 'DeFi · Base Mainnet',
    sub: 'DeFi · Base Mainnet · 12.4k followers',
    tags: [
      { label: 'Verified', variant: 'verified' },
      { label: 'DeFi' },
      { label: 'Genesis T2' },
    ],
    score: 72,
    scoreClass: 'hi',
    trend: '+12',
    trendClass: 'plt-up',
  },
  {
    id: 'baseswap',
    name: 'BaseSwap Pro',
    av: 'av-teal',
    letter: 'B',
    cat: 'DEX · Base Mainnet',
    sub: 'DEX · Base Mainnet · 9.8k followers',
    tags: [
      { label: 'Verified', variant: 'verified' },
      { label: 'DEX' },
    ],
    score: 68,
    scoreClass: 'mi',
    trend: '+5',
    trendClass: 'plt-up',
  },
  {
    id: 'zerolend',
    name: 'ZeroLend',
    av: 'av-purple',
    letter: 'Z',
    cat: 'Lending · Base Mainnet',
    sub: 'Lending · Base Mainnet · 18.2k followers',
    tags: [
      { label: 'Verified', variant: 'verified' },
      { label: 'Lending' },
      { label: 'Genesis T2' },
    ],
    score: null,
    scoreClass: 'na',
    trend: 'New',
    trendClass: 'plt-na',
  },
  {
    id: 'novadex',
    name: 'NovaDEX',
    av: 'av-red',
    letter: 'N',
    cat: 'DEX · Base Mainnet',
    sub: 'DEX · Base Mainnet · 7.1k followers',
    tags: [{ label: 'DEX' }],
    score: 41,
    scoreClass: 'lo',
    trend: '−18',
    trendClass: 'plt-down',
  },
  {
    id: 'aerobase',
    name: 'AeroBase',
    av: 'av-gold',
    letter: 'A',
    cat: 'AMM · Base Mainnet',
    sub: 'AMM · Base Mainnet · 14.6k followers',
    tags: [
      { label: 'Verified', variant: 'verified' },
      { label: 'AMM' },
      { label: 'Genesis T1' },
    ],
    score: 85,
    scoreClass: 'hi',
    trend: '+8',
    trendClass: 'plt-up',
  },
]

export const SEARCH_PROJECTS = [
  { name: 'Umia Protocol', cat: 'DeFi · Base Mainnet', av: 'av-blue', l: 'U' },
  { name: 'BaseSwap Pro', cat: 'DEX · Base Mainnet', av: 'av-teal', l: 'B' },
  { name: 'NovaDEX', cat: 'DEX · Base Mainnet', av: 'av-red', l: 'N' },
  { name: 'AeroBase', cat: 'AMM · Base Mainnet', av: 'av-gold', l: 'A' },
  { name: 'ZeroLend', cat: 'Lending · Base Mainnet', av: 'av-purple', l: 'Z' },
]
